-- Limpieza y actualización masiva de Soundscapes (16 pistas)
-- Asegura que todas las pistas tengan URLs correctas y mapeo de imágenes de alta calidad.
-- Incluye el campo is_premium para consistencia con el panel de administración.

ALTER TABLE soundscapes ADD COLUMN IF NOT EXISTS is_premium BOOLEAN DEFAULT FALSE;

INSERT INTO soundscapes (id, slug, name, description, audio_url, image_url, icon, color, recommended_for, is_premium)
VALUES 
('forest_meditation', 'forest_meditation', 'Bosque Profundo', 'Atmósfera natural y tranquila', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/forest_meditation.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/mindfulness_tecnica_008_monitorizacion-abierta.webp', 'leaf', '#4A6741', ARRAY['mindfulness', 'mañana'], false),
('atlantic_loop', 'atlantic_loop', 'Océano Atlántico', 'Olas constantes del océano', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/atlantic_loop.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/calmasos_tecnica_014_calma-oceanica.webp', 'water', '#1A1A2E', ARRAY['sueño', 'noche'], false),
('bird_relaxation', 'bird_relaxation', 'Jardín de Aves', 'Canto de pájaros y naturaleza', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/bird_relaxtion.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/calmasos_tecnica_001_respiracion-4-7-8.webp', 'rainy', '#4A90E2', ARRAY['sueño', 'ansiedad', 'foco'], false),
('deep_meditative', 'deep_meditative', 'Estado Profundo', 'Pad ambiental profundo', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/deep_meditative_state.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/calmasos_tecnica_013_s-o-s-rescate-de-panico.webp', 'water', '#2DD4BF', ARRAY['relajación', 'meditación'], false),
('meditation_bowls', 'meditation_bowls', 'Cuencos Sagrados', 'Sonidos de cuencos armónicos', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/meditation_bowls.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/calmasos_tecnica_002_respiracion-cuadrada-box-breathing-.webp', 'notifications', '#00B4D8', ARRAY['foco', 'energía'], false),
('tibetan_bowl', 'tibetan_bowl', 'Vibración Tibetana', 'Vibración tibetana pura', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/tibetan_singing_bowl.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/resiliencia_tecnica_010_visualizacion-negativa.webp', 'notifications-circle', '#ADB5BD', ARRAY['calma', 'meditación'], false),
('ethereal_voices', 'ethereal_voices', 'Voces Etéreas', 'Voces suaves del santuario', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/sanctuary_ethereal_voices.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/resiliencia_eter_092_gratitud-radical.webp', 'flame', '#FF6B35', ARRAY['cozy', 'invierno'], false),
('athmo_motion', 'athmo_motion', 'Cosmos', 'Pad de movimiento y relax', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/athmo_motion_pad.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/mindfulness_aria_072_el-observador-de-pensamientos.webp', 'planet', '#8A2BE2', ARRAY['relajación', 'sueño'], false),
('lotus_peace', 'lotus_peace', 'Paz de Loto', 'Calma pura y espiritual', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/nemaavla_lotus.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/resiliencia_tecnica_011_gratitud-recableado.webp', 'rose', '#9B59B6', ARRAY['meditación', 'espiritualidad'], false),
('moon_stretched', 'moon_stretched', 'Luna Mística', 'Vibración lunar expandida', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/synodic_moon_stretched.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/sueno_eter_113_respiracion-de-la-luna-chandra-bhedana-.webp', 'moon', '#87CEEB', ARRAY['paz', 'calma'], false),
('wind_chimes', 'wind_chimes', 'Viento Suave', 'Chimes y naturaleza viva', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/wind_chimes_birds_squirrel.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/mindfulness_aria_074_mindfulness-en-los-sonidos.webp', 'musical-notes', '#27AE60', ARRAY['naturaleza', 'mindfulness'], false),
('sirens_call_a', 'sirens_call_a', 'Canto de Sirena', 'Ambiente acuático misterioso', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/bigvegie_sirens_call_a.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/mindfulness_aria_071_escaner-corporal-para-el-dia.webp', 'pulse', '#4A90E2', ARRAY['sueño', 'visualización'], false),
('sirens_call_b', 'sirens_call_b', 'Profundidad Marina', 'Variante B del ambiente acuático', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/bigvegie_sirens_call_b.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/mindfulness_aria_075_consciencia-de-las-sensaciones-el-mapa-vivo-.webp', 'infinite', '#2C3E50', ARRAY['meditación', 'expansión'], false),
('meditative_motion', 'meditative_motion', 'Flujo Continuo', 'Pad rítmico para meditar', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/meditative_athmo_motionpad.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/resiliencia_eter_094_el-observador-de-la-tormenta.webp', 'heart', '#FF9F43', ARRAY['relajación', 'paz'], false),
('mountain_river', 'mountain_river', 'Montaña y Río', 'Agua fluyendo entre montañas', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/mountains_rivers_water.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/sueno_eter_112_el-lago-de-la-calma.webp', 'mountain', '#27AE60', ARRAY['naturaleza', 'paz'], false),
('night_crickets', 'night_crickets', 'Noche de Grillos', 'Serenata nocturna en el campo', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/soundscapes/night_cricket_ambience.mp3', 
  'https://ueuxjtyottluwkvdreqe.supabase.co/storage/v1/object/public/meditation-thumbnails/sueno_eter_110_preparacion-para-el-ensueno.webp', 'moon', '#1A1A2E', ARRAY['sueño', 'noche'], false)
ON CONFLICT (slug) DO UPDATE SET
  audio_url = EXCLUDED.audio_url,
  image_url = EXCLUDED.image_url,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  recommended_for = EXCLUDED.recommended_for,
  is_premium = EXCLUDED.is_premium;
